# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check: [format, lint, type-check, tests]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv with Python 3.13
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --dev

      - name: Ensure formatting
        if: matrix.check == 'format'
        run: uv run ruff format --check

      - name: Lint
        if: matrix.check == 'lint'
        run: uv run ruff check src tests

      - name: Type check
        if: matrix.check == 'type-check'
        run: uv run ty check

      - name: Run tests
        if: matrix.check == 'tests'
        run: uv run pytest
